### ISSUE TITLE
Ord implementation on EnumSetIter makes it difficult to use Iterator::max

### ISSUE THREAD

**Issue by dmarcuse** [Lymia/enumset#12]
`EnumSetIter` derives an implementation of `Ord`, which makes it annoying to use `Iterator::max` due to the conflicting name with `Ord::max`. This can be worked around with `iter.map(|v| v).max()`, or by manually disambiguating the call with `Iterator::max(iter)`, but both solutions feel a bit hacky.

I cloned and tested a fix for this by removing the `Ord` implementation, and the tests still compile and pass - I'm not sure why `PartialOrd`/`Ord` are implemented on an iterator in the first place. Unfortunately, removing the `Ord` implementation would be a breaking change according to semantic versioning.

**Comment by Lymia** [comment]
... yikes. I'll have to think about how to deal with this, I must have added those by accident via copy/paste.

**Comment by dmarcuse** [comment]
On second thought, it should be possible to add a feature flag that disables them, which would be a (technically) backwards-compatible change, right?

**Comment by Lymia** [comment]
No, a crate can enable the feature flag while another crate relies on it not being set. The same problem applies to introducing a new default feature flag that can be disabled.

**Comment by dmarcuse** [comment]
Oh well - I guess the only option would be to set it aside for the next major release?

**Comment by Lymia** [comment]
I believe so. One hack for now would be to add an inherent method that delegates to `Iterator::max` until the next major release.

**Comment by Lymia** [comment]
This will be fixed in the next major release.
