### ISSUE TITLE
Cannot use serde remote and serialize_as_list at the same time

### ISSUE THREAD

**Issue by joonazan** [Lymia/enumset#16]
```rust
#[derive(EnumSetType, Serialize, Deserialize)]
#[enumset(serialize_as_list)]
#[serde(remote = "UnitType")]
pub enum UnitTypeDSL {
    Explorer,
    Town,
    City,
    Dahan,
}
```

This code doesn't compile, complaining that Serialize is not implemented.

**Comment by joonazan** [comment]
I don't actually need this because I found a better way to do what I wanted to do. I looked a bit into enumset_derive but I have no idea why those two are incompatible.

**Comment by Lymia** [comment]
Have you checked if serde actually implements `Serialize` on the type itself when you use `#[serde(remote = ...)]`? This is probably on serde's side, `serialize_as_list` requires the type itself implement `Serialize` and `Deserialize`, and that is about all.

**Comment by joonazan** [comment]
I'm sorry that I missed your earlier reply.

Serde remote deserializes the annotated type first and then converts it into the type named in remote. At least that is how I assume it works. All other deserialize modifiers that I've used do work on remote-annotated data structures.
