### ISSUE TITLE
EnumSetType generates a Clippy warning in the latest nightlies

### ISSUE THREAD

**Issue by AlexTMjugador** [Lymia/enumset#25]
As explained in the issue title, `EnumSetType` generates a "use of irregular braces" warning that shows itself when a crate user adds a `#[derive(EnumSetType)` attribute to an enum.

This can be worked around by allowing the warning, but that's not so elegant.

### Clippy warning
![Clippy warning](https://user-images.githubusercontent.com/7822554/124516642-7201cc80-dde2-11eb-9f49-8317f7b2d985.png)

### rustc version
`rustc 1.55.0-nightly (b3d11f95c 2021-07-04)`

### clippy version
`clippy 0.1.55 (b3d11f9 2021-07-04)`

**Comment by Lymia** [comment]
This is strange. The only use of the `write!` macro I can find uses it with the standard `write!()` form. I'll look into it.

**Comment by Lymia** [comment]
This might be a clippy bug. I'm seeing no way for it to break otherwise, and I see a similar issue caused by a different crate: rust-lang/rust-clippy#7434

**Comment by Lymia** [comment]
The clippy bug seems to have been fixed recently. This should be dealt with...?

**Comment by AlexTMjugador** [comment]
I can confirm this is indeed fixed in Clippy version `0.1.55 (0271870 2021-07-22)`. Thanks for the headsup!
