### ISSUE TITLE
Cannot compile against num-traits v0.2.6

### ISSUE THREAD

**Issue by AlexArgoAi** [Lymia/enumset#3]
```
% cargo build
    Updating crates.io index
   Compiling num-traits v0.2.6                                                                                                                                                                                   
   Compiling enumset v0.3.11
error[E0308]: mismatched types
   --> src/lib.rs:139:27
    |
139 |         T::Repr::one() << bit as usize
    |                           ^^^^^^^^^^^^ expected u32, found usize

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `enumset`.

To learn more, run the command again with --verbose.
```

**Comment by Lymia** [comment]
I cannot reproduce this. What Rust version are you using?

**Comment by gyscos** [comment]
1.28, 1.29 and 1.30 all fail to build on linux x86_64.

**Comment by TerminalWitchcraft** [comment]
Same issue here with `Linux x86_64`, `rust 1.29`. Building fails with the above error message.

**Comment by Lymia** [comment]
Okey, I've reproduced it with the update to num-traits v0.2.6. Investigating.

**Comment by Lymia** [comment]
Is there a way to set up Travis to detect errors due to dependency updates like this?

**Comment by AlexArgoAi** [comment]
Travis will default to a clean build, which pulls the latest version of the dependencies. If you don't commit for a while, you could use a cron job to trigger a rebuild every week or so.
