### ISSUE TITLE
EnumSetType derive on newtype?

### ISSUE THREAD

**Issue by eikesr** [Lymia/enumset#7]
I expected this to work. Am I doing something wrong?
```
#[derive(EnumSetType)]                                              
pub struct MyAwesomeEnum(foo::my_enum);      
```

**Comment by Lymia** [comment]
Unfortunately, since custom derives work on the syntax level, there'd be no way to make this work, unless `EnumSetType` is already derived on `foo::my_enum` (in which case, why not use it directly?). `EnumSetType` needs to read the actual definition of the struct to properly implement the trait.
